### ISSUE TITLE
Prefix is not shown when using c!start

### ISSUE THREAD

**Issue by Androz2091** [NexInfinite/chess#1]
I'm getting this message when executing the `c!start` command, and the prefix is not the good one.
<img width="669" alt="Capture d’écran 2020-07-22 à 18 17 52" src="https://user-images.githubusercontent.com/42497995/88201454-c189cf80-cc47-11ea-89a7-7afefdc8d8c8.png">
Thanks

**Comment by NexInfinite** [comment]
The get_prefix is a function. You will need to use that to get the command. Something like
```python
data = open_json("prefixes.json")
prefix = data[ctx.guild.id]
```
would work. I am also using my [json_commands](https://github.com/NexInfinite/DiscordBotHelp/tree/master/Json%20Commands)
